# Generated by Django 6.0.6 on 2026-07-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_position_name_alter_worker_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigness',
            new_name='assignees',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
    ]
