# Generated by Django 6.0.6 on 2026-07-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_assigness_task_assignees_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(choices=[('Bug', 'Bug'), ('New_feature', 'New feature'), ('Breaking_change', 'Breaking change'), ('Refactoring', 'Refactoring'), ('QA', 'QA')], default='New_feature', max_length=25),
        ),
    ]
