# Generated by Django 6.0.6 on 2026-07-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_tasktype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(blank=True, choices=[('DEVELOPER', 'Developer'), ('Project_Manager', 'Project Manager'), ('QA', 'QA'), ('Designer', 'Designer'), ('DevOPS', 'DevOPS')], default='DEVELOPER', max_length=25, null=True),
        ),
    ]
