# Generated by Django 6.0.6 on 2026-07-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_worker_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(choices=[('Bug', 'Bug'), ('New feature', 'New feature'), ('Breaking change', 'Breaking change'), ('Refactoring', 'Refactoring'), ('QA', 'QA')], default='New feature', max_length=25),
        ),
    ]
